# Generated by Django 3.0.2 on 2020-06-06 05:41

from django.db import migrations, models
import tweets.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_auto_20200527_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(max_length=1000, validators=[tweets.validators.validate_content]),
        ),
    ]
